In [1]:
a = [1,5,6,8,9] # this is a list
print(a*2)

squre = []

for i in a:
    print(i**2)
    squre.append(i**2)
    
print("Squre:", squre)

[1, 5, 6, 8, 9, 1, 5, 6, 8, 9]
1
25
36
64
81
Squre: [1, 25, 36, 64, 81]


In [2]:
squre = [i**2 for i in a]

print(squre)

[1, 25, 36, 64, 81]


In [3]:
squre = [i**2 for i in a if i%2 == 0] # only process on even numbers

print(squre)

[36, 64]


In [4]:
import numpy as np

b = np.array(a) # change list into array
print(b)

c = np.array([[1,2,3],[3,4,5]])
print(c)
print(type(c))
print(b**2)

[1 5 6 8 9]
[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>
[ 1 25 36 64 81]


In [5]:
a0 = np.zeros((3,3))
print(a0)
a1 = np.ones((3,3))
print(a1)
a3 = np.full((3,3),3)
print(a3)
a4 = np.eye(3)
print(a4)
a5 = np.random.random((3,3))
print(a5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.61083063 0.89143017 0.28127597]
 [0.74892045 0.48275607 0.34728104]
 [0.57041711 0.06010283 0.48545788]]


In [6]:
a6 = np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])
b = a6[:2]
print(b)
b = a6[1:3]
print(b)
b = a6[:,:2]
print(b)
b = a6[:2,:2]
print(b)

[[1 2 3 4]
 [4 5 6 7]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [4 5]
 [8 9]]
[[1 2]
 [4 5]]


In [7]:
x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)

print(x+y)

print(np.multiply(x,y)) # mutiply elements in the same position

print(np.sum(x))

print(np.sum(x, axis=0))

print(np.sum(x, axis=1))

print(x.T)

[[ 6.  8.]
 [10. 12.]]
[[ 5. 12.]
 [21. 32.]]
10.0
[4. 6.]
[3. 7.]
[[1. 3.]
 [2. 4.]]


In [8]:
z = np.array([[1,2],[3,4],[5,6],[7,8]],dtype=np.float64)
g = np.array([1,2],dtype=np.float64)

print(z + g)

[[ 2.  4.]
 [ 4.  6.]
 [ 6.  8.]
 [ 8. 10.]]


In [9]:
from matplotlib.pyplot import imread, imsave

img = imread('test_image.jpg')
print(img)
print(img.dtype, img.shape)

img_tinted = img * [0., 0., 1.]

imsave('tinted.jpg', img_tinted/255)

[[[ 12  54  92]
  [  0  93 126]
  [  0 117 154]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 17  59  83]
  [  7  89 113]
  [  0 102 137]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 23  41  53]
  [ 14  67  83]
  [  4  79 108]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[  0  26   3]
  [  0  23   2]
  [  0  21   3]
  ...
  [  8  20  34]
  [  3   8  14]
  [  1   3   2]]

 [[  0  45   8]
  [  0  39   7]
  [  0  33   9]
  ...
  [ 19  36  54]
  [ 12  18  30]
  [  7   6  11]]

 [[  2  66  14]
  [  1  54  12]
  [  0  37   6]
  ...
  [ 13  49  71]
  [ 41  23  45]
  [ 20   7  14]]]
uint8 (513, 639, 3)
